plugins:
  autoprefixer:
    browsers:
      - 'Android >= 5.0'
      - 'iOS >= 8.0'
      - 'last 5 Chrome versions'
      - 'last 5 Firefox versions'
      - 'last 5 Opera versions'
      - 'IE >= 10'
      - 'last 2 Edge versions'
  cssnano:
