const { initialize } = require('./dev/config')
initialize(__dirname)

require('./dev/gulp/backend')
require('./dev/gulp/build')
require('./dev/gulp/dev-server')
require('./dev/gulp/e2e')
require('./dev/gulp/eslint')
require('./dev/gulp/integration')
require('./dev/gulp/proxy')
require('./dev/gulp/selenium')
require('./dev/gulp/serve')
require('./dev/gulp/test')
require('./dev/gulp/watch')
require('./dev/gulp/webpack')
